/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package selectcontract08;

import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author C0397554
 */
public class NewContract extends javax.swing.JDialog {

    /**
     * Creates new form NewContract
     * @param f
     * @param m
     * @param theContract
     */
    public NewContract(JFrame f, boolean m, Contract theContract) {
        super(f, m);
        initComponents();
        String [] cities = {"Victoria", "Vancouver", "Seattle", "Nanaimo", "Prince George"};
        final DefaultComboBoxModel model_1 = new DefaultComboBoxModel(cities);
        final DefaultComboBoxModel model_2 = new DefaultComboBoxModel(cities);
        newOriginCity.setModel(model_1);
        newDestCity.setModel(model_2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMessage = new javax.swing.JPanel();
        jOptionPane1 = new javax.swing.JOptionPane();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        newContractID = new javax.swing.JTextField();
        newOrder = new javax.swing.JTextField();
        jAddContract = new javax.swing.JButton();
        JCancelButton = new javax.swing.JButton();
        newOriginCity = new javax.swing.JComboBox<>();
        newDestCity = new javax.swing.JComboBox<>();
        jResetButton = new javax.swing.JButton();

        javax.swing.GroupLayout newMessageLayout = new javax.swing.GroupLayout(newMessage);
        newMessage.setLayout(newMessageLayout);
        newMessageLayout.setHorizontalGroup(
            newMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(newMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newMessageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        newMessageLayout.setVerticalGroup(
            newMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(newMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newMessageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label1.setText("ContractID");

        label2.setText("Origin City");

        label3.setText("Destination City");

        label4.setText("Order Item");

        newContractID.setToolTipText("one digit followed by 3 letters");

        jAddContract.setText("Add Contract");
        jAddContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddContractActionPerformed(evt);
            }
        });

        JCancelButton.setText("Cancel");
        JCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCancelButtonActionPerformed(evt);
            }
        });

        newOriginCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        newDestCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newOriginCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(newContractID, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newDestCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newOrder))))
                        .addGap(78, 78, 78))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jAddContract, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JCancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newContractID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newOriginCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newDestCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddContract)
                    .addComponent(JCancelButton)
                    .addComponent(jResetButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void JCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_JCancelButtonActionPerformed
    private void jAddContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddContractActionPerformed
        try{
            boolean checkID, checkItem, checkLoc, checkDup = true;
            String oCity = newOriginCity.getSelectedItem().toString();
            String dCity = newDestCity.getSelectedItem().toString();
            String nContractID = newContractID.getText().toUpperCase();
            String nOrderItem = newOrder.getText();
            checkID = nContractID.matches("^[0-9][a-zA-Z]{3}$");
            checkItem = nOrderItem.matches("([0-9]*\\s?[a-zA-Z]*[0-9]*[a-zA-Z]+[0-9]*[a-zA-Z]*\\s?[0-9]*)+");
            checkLoc = !oCity.equals(dCity);

            File inputFile = new File("C:\\Users\\manin\\OneDrive - Camosun College\\ICS 125\\selectcontract08\\SelectContract08\\src\\selectcontract08\\contracts.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(inputFile);
            doc.getDocumentElement().normalize();
            NodeList nList = doc.getElementsByTagName("contract");
        
        for (int temp = 0; temp < nList.getLength(); temp++) {
            Node nNode = nList.item(temp);
            System.out.println("\nCurrent Element :" + nNode.getNodeName());

            if (nNode.getNodeType() == Node.ELEMENT_NODE) {
               Element eElement = (Element) nNode;
               if(eElement.getElementsByTagName("contractID")
                       .item(0).getTextContent().matches(nContractID)){
                   checkDup = false;
                   break;
               }
            }
        }
        if(checkID && checkItem && checkLoc && checkDup){
            Element newContract = doc.createElement("contract");
            
            Element contractID = doc.createElement("contractID");
            contractID.appendChild(doc.createTextNode(nContractID));
            newContract.appendChild(contractID);
            
            Element originCity = doc.createElement("originCity");
            originCity.appendChild(doc.createTextNode(oCity));
            newContract.appendChild(originCity);
            
            Element destCity = doc.createElement("destCity");
            destCity.appendChild(doc.createTextNode(dCity));
            newContract.appendChild(destCity);
            
            Element orderItem = doc.createElement("orderItem");
            orderItem.appendChild(doc.createTextNode(nOrderItem));
            newContract.appendChild(orderItem);
            
            Element root = doc.getDocumentElement();
            root.appendChild(newContract);
            
            DOMSource source = new DOMSource(doc);
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            StreamResult result = new StreamResult("C:\\Users\\manin\\OneDrive - Camosun College\\ICS 125\\selectcontract08\\SelectContract08\\src\\selectcontract08\\contracts.xml");
            transformer.transform(source, result);
            
            jResetButtonActionPerformed(evt);
            jOptionPane1.showMessageDialog(newMessage, "New Contract Saved");
        } else {
            if(!checkID){
                jOptionPane1.showMessageDialog(newMessage, "Please note the only"
                        + " valid inputs for Contract ID follow the 1 number 3 letters format");
            } else if(!checkDup){
                jOptionPane1.showMessageDialog(newMessage, "Contract " + nContractID + " already defined.");
            } else if(!checkLoc){
                jOptionPane1.showMessageDialog(newMessage, "Please "
                    + "note you cannot have the same origin and destination city");
            } else {
                jOptionPane1.showMessageDialog(newMessage, "Please "
                    + "note you cannot only use numbers in your order");
            } 
        }
      } catch (Exception e) { e.printStackTrace(); }
    }//GEN-LAST:event_jAddContractActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        newContractID.setText("");
        newOrder.setText("");
        newOriginCity.setSelectedIndex(0);
        newDestCity.setSelectedIndex(0);
    }//GEN-LAST:event_jResetButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCancelButton;
    private javax.swing.JButton jAddContract;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JButton jResetButton;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JTextField newContractID;
    private javax.swing.JComboBox<String> newDestCity;
    private javax.swing.JPanel newMessage;
    private javax.swing.JTextField newOrder;
    private javax.swing.JComboBox<String> newOriginCity;
    // End of variables declaration//GEN-END:variables
}
