/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package selectcontract08;

import java.awt.GridLayout;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author C0397554
 */
public class ViewBids extends java.awt.Dialog {
    /**
     * Creates new form ViewBids
     * @param f
     * @param m
     * @throws java.io.IOException
     * @throws org.json.simple.parser.ParseException
     */
    public ViewBids(JFrame f, boolean m) throws IOException, ParseException {
        super(f, m);
        initComponents();
        
        GridLayout frame = new GridLayout(0,4, 0, 0);

        jBidView.setLayout(frame);
        try{
            Object obj = new JSONParser().parse(new FileReader("C:\\Users\\manin\\OneDrive - Camosun College\\ICS 125\\selectcontract08\\SelectContract08\\src\\selectcontract08\\bid.json"));
            JSONArray bidObject = (JSONArray) obj;
            
            for(int i = 0; i < bidObject.size(); i++){               
                JSONObject bid = (JSONObject) bidObject.get(i);
                String name = (String) bid.get("name");
                String contractID = (String) bid.get("contractID");
                String date = (String) bid.get("date");
                String price = (String) bid.get("amount");
                
                jBidView.add(new JLabel(name, SwingConstants.CENTER));
                jBidView.add(new JLabel(contractID, SwingConstants.CENTER));
                jBidView.add(new JLabel(date, SwingConstants.CENTER));
                jBidView.add(new JLabel(price, SwingConstants.CENTER));  
            }
            
        } catch(FileNotFoundException e){
            System.out.println("problem occured");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBidView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jBidView.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ContractID");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Date");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Amount");

        javax.swing.GroupLayout jBidViewLayout = new javax.swing.GroupLayout(jBidView);
        jBidView.setLayout(jBidViewLayout);
        jBidViewLayout.setHorizontalGroup(
            jBidViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBidViewLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(93, 93, 93)
                .addComponent(jLabel3)
                .addGap(188, 188, 188)
                .addComponent(jLabel4)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jBidViewLayout.setVerticalGroup(
            jBidViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBidViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBidViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBidView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jBidView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBidView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
